import 'share/quarto/files/quarto.just'
set allow-duplicate-recipes := true

np := if os() == "macos" {`sysctl -n hw.ncpu`} else if os() == "linux" {`nproc`} else {"1"}

default:
  just --list

clean:
  find . -name '.DS_Store' -type f -delete

setup: git-ignore

setup-quarto:
  cp -n -r share/quarto/* {{invocation_directory()}}

git-ignore:
  cp share/.gitignore {{invocation_directory()}}

julia-new-package name:
  #!/usr/bin/env julia
  using PkgTemplates
  Template(interactive=true)({{name}})

log:
  just julia-new-package Discontinuity.jl