import? 'scripts/languages.just'
import? 'scripts/github.just'

[private]
default:
    just --list --justfile ~/justfile

update: update-config sync-projects

update-config:
    -chezmoi update

update-pkgs:
    -cargo install garden-tools
    -curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    -cargo binstall --strategies crate-meta-data jj-cli typst-cli

sync: sync-projects sync-overleaf

sync-projects:
    #!/usr/bin/env bash
    for cfg in ~/.config/garden/{garden,JuliaSpacePhysics}.yaml; do
        garden -c "$cfg" grow "*"
        garden -c "$cfg" cmd "*" pull -j4
        garden -c "$cfg" cmd "*" status
    done


[private]
sync-overleaf:
    cd ~/projects/share && just sync-overleaf

backup-config:
    #!/usr/bin/env sh
    mackup backup --force

[private]
backup-pictures:
    rclone sync ~/Pictures BoxUCLA:Pictures --progress

# restoring the configuration using mackup
restore-config:
    #!/usr/bin/env sh
    echo "Syncing applications with 'mackup'..."
    mackup restore --force

[private]
link:
    ln -s ~/.claude/CLAUDE.md ~/.codex/AGENTS.md
    ln -s ~/Library/CloudStorage/Box-Box/research ~/research

[private]
migrate:
    rclone sync GoogleDriveUCLA:library BoxUCLA:library --progress
    ln -s "/Volumes/My Passport for Mac/data" ~/data

clean:
    -brew cleanup
    -pixi clean cache --yes

[private]
disk-usage:
    gdu-go --ignore-dirs-pattern '.*CloudStorage'
    gdu-go / -I '.*CloudStorage'

# extract_figures from a PDF file
extract_figures +pdf_file:
    ~/scripts/extract_figures.py {{ pdf_file }}
