default:
  just --list

rustup:
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

juliaup:
  #!/usr/bin/env bash
  echo "Juliaup - Julia version manager..."
  if ! command -v juliaup; then
    curl -fsSL https://install.julialang.org | sh -s -- --yes
  fi

julia-pkgs: juliaup
  #!/usr/bin/env julia
  using Pkg
  Pkg.add("Pluto")
