#!/usr/bin/env sh

# bsp or float (default: float)
echo "yabai configuration loaded.."

# example: render all unfocused windows with 90% opacity
# yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.2

# --grid <rows>:<cols>:<start-x>:<start-y>:<width>:<height>
yabai -m rule --add title="Emacs Everywhere.*" display=mouse grid=3:3:1:1:1:1 manage=off

# Move the activated app to the current mouse position and focus it
yabai -m signal --add event=application_activated \
	app="(iTerm2|WezTerm|Zed)" \
	action="yabai -m window --display mouse --focus"

yabai -m signal --add event=application_visible \
	app="espanso" \
	action="yabai -m window --display mouse --focus"