#!/usr/bin/env sh

# bsp or float (default: float)
echo "yabai configuration loaded.."

# --grid <rows>:<cols>:<start-x>:<start-y>:<width>:<height>
yabai -m rule --add title="Emacs Everywhere.*" display=mouse grid=3:3:1:1:1:1 manage=off

# Move the activated app to the current mouse position and focus it
yabai -m signal --add event=application_activated \
	app="iTerm2$" \
	action="yabai -m window --display mouse --focus"